---
title: "Our Course Project"
sidebar: false 
---

I'm honored to be a member of the \[QuantFlare\] project

Below, you'll find a brief summary of our project. To access a detailed project description, please go to <https://drive.google.com/file/d/1kiejhGSntJjeWOBp5D3TTWrPg0r2rnSw/view?usp=drive_link>[\]](#0){.uri}.

**Summary**

\[The datasets "number of foreign babies by year" and "population growth rate in Turkey" are among those we have selected. Working with this dataset piques our curiosity because it can be used for a wide range of potential analysis. Furthermore, we think it offers insightful information about shifts in Turkey's demographic composition. When interpreted, the data can have significance and span a wide range of observable issues. We believe it would be helpful to compare Turkey's total population growth rate with the growth rate of the foreign population and show the demographic changes, even though we are unsure of the precise tasks for the project's future stages. The required population data by city and year is provided by the datasets we will be working with, enabling us to investigate variations in changes in the demographic structure of different cities.\]
